#!/usr/bin/env python3
import click
import duckdb

from decoy import register_en


@click.group()
def cli():
    pass


@cli.command()
def generate():
    con = duckdb.connect("test.duckdb")
    register_en(con)
    count = 50
    con.execute("DROP TABLE IF EXISTS test;")
    con.execute(
        f"""
CREATE TABLE test AS SELECT
decoy_en('name') as name
FROM range({count})"""
    )
    con.execute("SELECT * from test LIMIT 20")
    res = con.fetchall()
    for row in res:
        print(row)


@cli.command()
def shuffle():
    con = duckdb.connect("test.duckdb")
    register_en(con)
    count = 50
    con.execute(
        f"""
SELECT name,
shuffle(name) as arrow
FROM test;"""
    )
    res = con.fetchall()
    for row in res:
        print(row)


if __name__ == "__main__":
    cli()
